# A faily standard FedAvg strategy for FLower

_target_: flwr.server.strategy.FedAvg # we point to a class (in the code we will use `hydra.utils.instantiate(<this_node>)` to create the object)
_recursive_: true # we want everything to be instantiated
fraction_fit: 0.44 
fraction_evaluate: 0 
min_fit_clients: 2
min_available_clients: ${server.pool}
on_fit_config_fn:
  _target_: src.server.gen_fit_config # function to call eventually
  fit_cfg: ${server.fit_cfg}